#
#
#  C++ Portable Types Library (PTypes)
#  Version 2.0.2  Released 17-May-2004
#
#  Copyright (C) 2001-2004 Hovik Melikyan
#
#  http://www.melikyan.com/ptypes/
#
#
#
# Makefile for Linux, called from ../Makefile
#

CXX = g++

OS_CXXOPTS = -pthread

include Makefile.common

