// generated by recomp_gen.py -- do not edit
bool DSP::runRecompiled(const TWord _pc) noexcept
{
	if (_pc != 0x100091) return false;
	m_interruptFunc(this);
	// $100091: 43d900
	pcCurrentInstruction = 0x100091; reg.pc.var = 0x100092; m_opWordB = 0x0127cdu; m_currentOpLen = 1;
	op_Movel_ea(0x43d900u);
	++m_instructions;
	// $100092: 0127cd
	pcCurrentInstruction = 0x100092; reg.pc.var = 0x100093; m_opWordB = 0x012586u; m_currentOpLen = 1;
	op_Mpy_su(0x0127cdu);
	++m_instructions;
	// $100093: 012586
	pcCurrentInstruction = 0x100093; reg.pc.var = 0x100094; m_opWordB = 0x01268cu; m_currentOpLen = 1;
	op_Dmac(0x012586u);
	++m_instructions;
	// $100094: 01268c
	pcCurrentInstruction = 0x100094; reg.pc.var = 0x100095; m_opWordB = 0x01248fu; m_currentOpLen = 1;
	op_Macsu(0x01268cu);
	++m_instructions;
	// $100095: 01248f
	pcCurrentInstruction = 0x100095; reg.pc.var = 0x100096; m_opWordB = 0x43e132u; m_currentOpLen = 1;
	op_Dmac(0x01248fu);
	++m_instructions;
	// $100096: 43e132
	pcCurrentInstruction = 0x100096; reg.pc.var = 0x100097; m_opWordB = 0x200034u; m_currentOpLen = 1;
	{
		const auto preA = reg.a, preB = reg.b;
		op_Asl_D(0x43e132u);
		const auto postA = reg.a, postB = reg.b;
		reg.a = preA; reg.b = preB;
		op_Movel_ea(0x43e132u);
		if (postA != preA) reg.a = postA;
		if (postB != preB) reg.b = postB;
	}
	++m_instructions;
	// $100097: 200034
	pcCurrentInstruction = 0x100097; reg.pc.var = 0x100098; m_opWordB = 0x000000u; m_currentOpLen = 1;
	op_Sub_SD(0x200034u);
	++m_instructions;
	// $100098: 000000
	pcCurrentInstruction = 0x100098; reg.pc.var = 0x100099; m_opWordB = 0x486100u; m_currentOpLen = 1;
	op_Nop(0x000000u);
	++m_instructions;
	// $100099: 486100
	pcCurrentInstruction = 0x100099; reg.pc.var = 0x10009a; m_opWordB = 0x5e5800u; m_currentOpLen = 1;
	op_Movel_ea(0x486100u);
	++m_instructions;
	// $10009a: 5e5800
	pcCurrentInstruction = 0x10009a; reg.pc.var = 0x10009b; m_opWordB = 0x05f421u; m_currentOpLen = 1;
	opCE_Movey_ea<0u, 3u>(0x5e5800u);
	++m_instructions;
	return true;
}
