#!/usr/bin/env python3
# Whole-program static recompiler, step 2: turn mnm-recomp-discover's trace into dsp56k_recomp.inl.
#   recomp_gen2.py <disc.txt> <nm -C of the discover binary> > dsp56k_recomp.inl
# Blocks are basic blocks over the traced code: they start at every leader (an entry point, the instruction
# after anything that ends a block, the instruction after a DO loop end) and run until the next leader, an
# untraced or never-recompiled instruction, a block-ending instruction (included), or MAX_INSTR.
import sys, re
MAX_INSTR = 64

syms = {}
for l in open(sys.argv[2]):
    m = re.match(r'([0-9a-f]+) [tTwW] (?:void )?dsp56k::DSP::(\w+(?:<[^()]*>)?)\(unsigned int\)$', l.strip())
    if m: syms[int(m.group(1), 16)] = m.group(2)

ins, entries, loopends = {}, set(), set()
for l in open(sys.argv[1]):
    f = l.split()
    if f[0] == 'I':
        pc = int(f[1], 16)
        ins[pc] = dict(a=int(f[2], 16), b=int(f[3], 16), len=int(f[4]), kind=int(f[5]), par=f[6] == '1',
                       op=int(f[7], 16), mv=int(f[8], 16), alu=int(f[9], 16), count=int(f[10]),
                       moveAB=f[11] == '1', readsPC=f[12] == '1')
    elif f[0] == 'E': entries.add(int(f[1], 16))
    elif f[0] == 'L': loopends.add(int(f[1], 16))

leaders = set(entries) | {la + 1 for la in loopends}
for pc, i in ins.items():
    if i['kind'] != 0: leaders.add(pc + i['len'])

def handler(off):
    if off not in syms: raise KeyError(f'no symbol for handler offset {off:x}')
    return syms[off]

blocks = []
for start in sorted(leaders):
    if start not in ins or ins[start]['kind'] == 2: continue
    pcs, pc = [], start
    while pc in ins and ins[pc]['kind'] != 2 and len(pcs) < MAX_INSTR:
        if pcs and pc in leaders: break
        pcs.append(pc)
        if ins[pc]['kind'] == 1: break
        pc += ins[pc]['len']
    blocks.append(pcs)

out = ['// generated by recomp_gen2.py from a mnm-recomp-discover trace -- do not edit', '']
total_instr = 0
for pcs in blocks:
    start = pcs[0]
    nwords = pcs[-1] + ins[pcs[-1]]['len'] - start
    words = []
    for pc in pcs:
        i = ins[pc]; words.append(i['a'])
        if i['len'] == 2: words.append(i['b'])
    out.append(f'static constexpr TWord g_recompWords_{start:06x}[] = {{{", ".join(f"0x{w:06x}" for w in words)}}};')
    out.append(f'template<> __attribute__((flatten)) bool DSP::recompBlock<0x{start:06x}>(DSP* d) noexcept')
    out.append('{')
    for n, pc in enumerate(pcs):
        i = ins[pc]; op = f'0x{i["a"]:06x}u'
        h = handler(i['op']) if not i['par'] else ''
        # PC bookkeeping only where a handler reads it: control flow (kind 1, always a block's last
        # instruction), anything that reads PC, LRA/STOP. The block's final PC is written once at its end.
        if i['kind'] == 1 or i['readsPC'] or h.startswith(('op_Lra', 'op_Stop')):
            out.append(f'\td->pcCurrentInstruction = 0x{pc:06x}; d->reg.pc.var = 0x{pc + 1:06x};')
        if i['len'] == 2:
            out.append(f'\td->m_opWordB = 0x{i["b"]:06x}u;')
        if i['par'] and i['moveAB']:
            # the move reads/writes A or B: reproduce exec_parallel's latch (move sees pre-ALU A/B)
            out += ['\t{', '\t\tconst auto preA = d->reg.a, preB = d->reg.b;', f'\t\td->{handler(i["alu"])}({op});',
                    '\t\tconst auto postA = d->reg.a, postB = d->reg.b;', '\t\td->reg.a = preA; d->reg.b = preB;',
                    f'\t\td->{handler(i["mv"])}({op});', '\t\tif (postA != preA) d->reg.a = postA;',
                    '\t\tif (postB != preB) d->reg.b = postB;', '\t}']
        elif i['par']:
            # the move doesn't touch A or B, so ALU-then-move is exactly what the latch would produce
            out += [f'\td->{handler(i["alu"])}({op});', f'\td->{handler(i["mv"])}({op});']
        else:
            out.append(f'\td->{h}({op});')
    out.append(f'\td->m_instructions += {len(pcs)};')   # once per block, like the JIT
    last = pcs[-1]
    if ins[last]['kind'] != 1:
        out.append(f'\td->pcCurrentInstruction = 0x{last:06x}; d->reg.pc.var = 0x{last + ins[last]["len"]:06x};')
    out += ['\treturn true;', '}', '']
    blocks_words = nwords
    total_instr += len(pcs)

starts = [b[0] for b in blocks]
base, top = min(starts), max(b[-1] for b in blocks)
maxw = max(b[-1] + ins[b[-1]]['len'] - b[0] for b in blocks)
out.append('const DSP::RecompProgram* DSP::recompProgram()')
out.append('{')
out.append('\tstatic const RecompBlock blocks[] = {')
out.append('\t\t{nullptr, nullptr, 0, 0},')
for b in blocks:
    nw = b[-1] + ins[b[-1]]['len'] - b[0]
    out.append(f'\t\t{{&DSP::recompBlock<0x{b[0]:06x}>, g_recompWords_{b[0]:06x}, 0x{b[0]:06x}, {nw}}},')
out.append('\t};')
out.append('\tstatic const std::vector<uint16_t> index = [] {')
out.append(f'\t\tstd::vector<uint16_t> v(0x{top - base + 1:x} + {maxw}, 0);   // + maxw: covered[] shares this size')
out.append('\t\tfor (size_t i = 1; i < sizeof(blocks) / sizeof(blocks[0]); ++i)')
out.append(f'\t\t\tv[blocks[i].pc - 0x{base:06x}] = static_cast<uint16_t>(i);')
out.append('\t\treturn v;')
out.append('\t}();')
out.append('\tstatic const std::vector<uint8_t> covered = [] {')
out.append(f'\t\tstd::vector<uint8_t> v(0x{top - base + 1:x} + {maxw}, 0);')
out.append('\t\tfor (size_t i = 1; i < sizeof(blocks) / sizeof(blocks[0]); ++i)')
out.append('\t\t\tfor (TWord w = 0; w < blocks[i].numWords; ++w)')
out.append(f'\t\t\t\tv[blocks[i].pc - 0x{base:06x} + w] = 1;')
out.append('\t\treturn v;')
out.append('\t}();')
out.append(f'\tstatic const RecompProgram program{{blocks, sizeof(blocks) / sizeof(blocks[0]), index.data(), covered.data(), TWord(index.size()), 0x{base:06x}, {maxw}}};')
out.append('\treturn &program;')
out.append('}')
assert len(blocks) < 65535
print('\n'.join(out))
covered = sum(ins[pc]['count'] for b in blocks for pc in b)
alln = sum(i['count'] for i in ins.values())
sys.stderr.write(f'{len(blocks)} blocks, {total_instr} instructions, avg {total_instr/len(blocks):.1f}/block, '
                 f'max {maxw} words; covers {100*covered/alln:.2f}% of executed instructions\n')
