#!/usr/bin/env python3
# recomp_gen.py <gen.txt> <nm -C output> > dsp56k_recomp.inl
import sys, re
syms = {}
for l in open(sys.argv[2]):
    m = re.match(r'([0-9a-f]+) [tTwW] (?:void )?dsp56k::DSP::(\w+(?:<[^()]*>)?)\(unsigned int\)$', l.strip())
    if m: syms[int(m.group(1), 16)] = m.group(2)
def call(o, op):
    name = syms[int(o, 16)]
    return f'{name}(0x{op}u);'
rows = [l.split() for l in open(sys.argv[1]) if re.match(r'^[0-9a-f]{6} ', l)]
out = ['// generated by recomp_gen.py -- do not edit', '__attribute__((flatten)) bool DSP::runRecompiled(const TWord _pc) noexcept', '{',
       f'\tif (_pc != 0x{rows[0][0]}) return false;', '\tm_interruptFunc(this);']
for pc, wa, wb, par, op, mv, alu in rows:
    out.append(f'\t// ${pc}: {wa}')
    out.append(f'\tpcCurrentInstruction = 0x{pc}; reg.pc.var = 0x{int(pc,16)+1:06x}; m_opWordB = 0x{wb}u; m_currentOpLen = 1;')
    if par == '1':
        out += ['\t{', '\t\tconst auto preA = reg.a, preB = reg.b;', f'\t\t{call(alu, wa)}',
                '\t\tconst auto postA = reg.a, postB = reg.b;', '\t\treg.a = preA; reg.b = preB;', f'\t\t{call(mv, wa)}',
                '\t\tif (postA != preA) reg.a = postA;', '\t\tif (postB != preB) reg.b = postB;', '\t}']
    else:
        out.append(f'\t{call(op, wa)}')
    out.append('\t++m_instructions;')
out += ['\treturn true;', '}']
print('\n'.join(out))
